version: '3'
services:
  web:
    #build: . #'.' by convention searches for a file named 'Dockerfile'
    build:
      context: . #location of the files in our project, useful if files are not in same dir as the compose file 
      dockerfile: Dockerfile
    ports:
      - "80:80"
